### ISSUE TITLE
where to find stream.h

### ISSUE THREAD

**Issue by lizhanglz** [kpn-iot/senml-c-library#2]
Hi I am trying to build this library on Ubuntu 16.04 and got missing stream.h error. Have been googling this header file but the closet I can find is Arduino's "Stream.h". Can you let me know where to find this file, and what other dependencies I would need to build it on Linux? Thanks.

**Comment by jan-bogaerts** [comment]
This could indeed be a problem with capitals. The library was built on a windows machine that doesn't really care about capitals in filenames. Try changing it to Stream.h in your code?

**Comment by jan-bogaerts** [comment]
Hi,
There are no plans to make a pure linux version at the moment. You can try to start from the mbed version though cause the libraries used by mbed should be closer to posix standard. (If memory serves me correct, the library uses some defines to switch between arduino and mbed).
